// 메뉴 데이터입니다. price는 "센트" 단위 정수(USD)입니다. 예: 300 = $3.00
// (실수 대신 정수 센트로 저장해 소수점 합산 오차를 방지합니다.)
// hasTemp: true인 카테고리(커피/라떼/티)는 주문 화면에 HOT/ICE 토글이 함께 표시됩니다.
// isExtra: true인 카테고리(추가요청)는 수량 대신 켬/끔(선택) 방식 칩으로 표시됩니다.
// available: false인 항목은 화면에는 보이지만 선택할 수 없고, 누르면 "출시 예정" 안내가 뜹니다.
// 가격(price)은 사용자 주문 화면과 인쇄 라벨에는 표시되지 않고,
// 관리자 페이지의 "전체 내역" 탭에서만 보입니다.

export const CATEGORIES = [
  {
    id: "coffee",
    nameKo: "커피",
    nameEn: "Coffee",
    emoji: "☕️",
    hasTemp: true,
    items: [
      { id: "americano", nameKo: "아메리카노", nameEn: "Americano", price: 300, available: true },
      { id: "cafe-latte", nameKo: "카페라떼", nameEn: "Caffè Latte", price: 350, available: true },
      { id: "vanilla-latte", nameKo: "바닐라라떼", nameEn: "Vanilla Latte", price: 400, available: true },
      { id: "mocha-latte", nameKo: "모카라떼", nameEn: "Mocha Latte", price: 450, available: true },
      { id: "caramel-macchiato", nameKo: "카라멜마끼야또", nameEn: "Caramel Macchiato", price: 450, available: true },
      { id: "cinnamon-dolce", nameKo: "시나몬돌체", nameEn: "Cinnamon Dolce", price: 450, available: true },
      { id: "hazelnut-latte", nameKo: "헤이즐넛라떼", nameEn: "Hazelnut Latte", price: 450, available: true },
      { id: "condensed-milk-latte", nameKo: "연유라떼", nameEn: "Condensed Milk Latte", price: 450, available: true },
      { id: "ajae-coffee", nameKo: "아재커피", nameEn: "Ajae Coffee", price: 450, available: true },
    ],
  },
  {
    id: "latte",
    nameKo: "라떼",
    nameEn: "Latte",
    emoji: "🍵",
    hasTemp: true,
    items: [
      { id: "matcha-latte", nameKo: "말차라떼", nameEn: "Matcha Latte", price: 500, available: true },
      { id: "choco-latte", nameKo: "초코라떼", nameEn: "Choco Latte", price: 400, available: true },
      { id: "nutty-cream-latte", nameKo: "너티크림라떼", nameEn: "Nutty Cream Latte", price: 400, available: false },
      { id: "milk-tea", nameKo: "밀크티", nameEn: "Milk Tea", price: 400, available: false },
      { id: "sweet-potato-latte", nameKo: "고구마라떼", nameEn: "Sweet Potato Latte", price: 400, available: false },
      {
        id: "walnut-almond-grain-latte",
        nameKo: "호두아몬드곡물라떼",
        nameEn: "Walnut Almond Grain Latte",
        price: 400,
        available: false,
      },
      { id: "earl-grey-milk-tea", nameKo: "얼그레이밀크티", nameEn: "Earl Grey Milk Tea", price: 500, available: false },
      { id: "mugwort-latte", nameKo: "쑥라떼", nameEn: "Mugwort Latte", price: 500, available: false },
    ],
  },
  {
    id: "tea",
    nameKo: "티",
    nameEn: "Tea",
    emoji: "🍃",
    hasTemp: true,
    items: [
      { id: "ginger-citron-tea", nameKo: "생강유자차", nameEn: "Ginger Citron Tea", price: 300, available: true },
      { id: "bellflower-ginger-tea", nameKo: "도라지생강차", nameEn: "Bellflower Ginger Tea", price: 300, available: true },
      { id: "strawberry-milk-tea", nameKo: "딸기밀크티", nameEn: "Strawberry Milk Tea", price: 300, available: true },
      { id: "caramel-milk-tea", nameKo: "카라멜밀크티", nameEn: "Caramel Milk Tea", price: 300, available: true },
      { id: "sweet-chamomile-tea", nameKo: "스윗캐모마일티", nameEn: "Sweet Chamomile Tea", price: 300, available: true },
      { id: "peach-tea", nameKo: "복숭아티", nameEn: "Peach Tea", price: 300, available: true },
      {
        id: "grapefruit-honey-black-tea",
        nameKo: "자몽허니블랙티",
        nameEn: "Grapefruit Honey Black Tea",
        price: 300,
        available: false,
      },
      { id: "apple-chamomile-tea", nameKo: "사과캐모마일티", nameEn: "Apple Chamomile Tea", price: 300, available: false },
    ],
  },
  {
    id: "ade",
    nameKo: "에이드",
    nameEn: "Ade",
    emoji: "🍹",
    hasTemp: false,
    items: [
      { id: "green-grape-ade", nameKo: "청포도에이드", nameEn: "Green Grape Ade", price: 400, available: true },
      { id: "passion-fruit-ade", nameKo: "패션프루츠에이드", nameEn: "Passion Fruit Ade", price: 400, available: true },
      { id: "peach-ade", nameKo: "복숭아에이드", nameEn: "Peach Ade", price: 400, available: true },
      { id: "grapefruit-ade", nameKo: "자몽에이드", nameEn: "Grapefruit Ade", price: 400, available: false },
      { id: "apple-mango-ade", nameKo: "애플망고에이드", nameEn: "Apple Mango Ade", price: 400, available: false },
      { id: "hallabong-ade", nameKo: "한라봉에이드", nameEn: "Hallabong Ade", price: 400, available: false },
    ],
  },
  {
    id: "smoothie",
    nameKo: "스무디",
    nameEn: "Smoothie",
    emoji: "🥤",
    hasTemp: false,
    items: [
      { id: "blueberry-smoothie", nameKo: "블루베리스무디", nameEn: "Blueberry Smoothie", price: 500, available: true },
      { id: "strawberry-smoothie", nameKo: "딸기스무디", nameEn: "Strawberry Smoothie", price: 500, available: true },
      { id: "mango-smoothie", nameKo: "망고스무디", nameEn: "Mango Smoothie", price: 500, available: true },
      {
        id: "peach-strawberry-smoothie",
        nameKo: "피치스트로베리스무디",
        nameEn: "Peach Strawberry Smoothie",
        price: 400,
        available: true,
      },
      {
        id: "mint-choco-java-chip-smoothie",
        nameKo: "민트초코자바칩스무디",
        nameEn: "Mint Choco Java Chip Smoothie",
        price: 500,
        available: true,
      },
    ],
  },
  {
    id: "ice-cream",
    nameKo: "아이스크림",
    nameEn: "Ice Cream",
    emoji: "🍨",
    hasTemp: false,
    items: [
      { id: "vanilla-ice-cream", nameKo: "바닐라아이스크림", nameEn: "Vanilla Ice Cream", price: 200, available: true },
      { id: "choco-ice-cream", nameKo: "초코아이스크림", nameEn: "Chocolate Ice Cream", price: 200, available: true },
      { id: "strawberry-ice-cream", nameKo: "딸기아이스크림", nameEn: "Strawberry Ice Cream", price: 200, available: true },
      {
        id: "haagen-dazs-choco-vanilla",
        nameKo: "하겐다즈초코바닐라",
        nameEn: "Häagen-Dazs Choco Vanilla",
        price: 300,
        available: true,
      },
    ],
  },
  {
    id: "extra",
    nameKo: "추가요청",
    nameEn: "Extra Requests",
    emoji: "➕",
    hasTemp: false,
    isExtra: true,
    items: [
      { id: "less-ice", nameKo: "얼음적게", nameEn: "Less Ice", price: 0, available: true },
      { id: "more-ice", nameKo: "얼음많이", nameEn: "More Ice", price: 0, available: true },
      { id: "no-ice", nameKo: "얼음없이", nameEn: "No Ice", price: 0, available: true },
      { id: "extra-shot", nameKo: "샷추가", nameEn: "Extra Shot", price: 100, available: true },
      { id: "lychee-jelly", nameKo: "리치젤리추가", nameEn: "Lychee Jelly Add-on", price: 300, available: true },
      { id: "extra-syrup", nameKo: "시럽추가", nameEn: "Extra Syrup", price: 50, available: true },
      { id: "oat-milk", nameKo: "오트밀우유", nameEn: "Oat Milk", price: 0, available: true },
      { id: "less-sweet", nameKo: "안달게", nameEn: "Less Sweet", price: 0, available: true },
    ],
  },
];
